// COM5113 Full_Search_UI - WinForms Option A
// Generated by assistant

using System.Collections.Generic;

namespace FullSearch
{
    public class BestFirst : IPathFinder
    {
        public string Name => "BestFirst";

        public List<Coord> FindPath(int[,] terrain, Coord start, Coord goal)
        {
            int rows = terrain.GetLength(0), cols = terrain.GetLength(1);
            var visited = new bool[rows, cols];
            var open = new PriorityQueue();
            var startNode = new SearchNode(start) { HCost = SearchUtilities.Manhattan(start, goal) };
            open.Enqueue(startNode);

            while (!open.IsEmpty())
            {
                var node = open.Dequeue();
                if (visited[node.Position.Row, node.Position.Col]) continue;
                visited[node.Position.Row, node.Position.Col] = true;

                if (node.Position.Equals(goal)) return SearchUtilities.BuildPathList(node);

                foreach (var nb in SearchUtilities.GetNeighbors(node.Position))
                {
                    if (nb.Row < 0 || nb.Row >= rows || nb.Col < 0 || nb.Col >= cols) continue;
                    if (terrain[nb.Row, nb.Col] == 0) continue;
                    if (visited[nb.Row, nb.Col]) continue;
                    var newNode = new SearchNode(nb) { Predecessor = node, HCost = SearchUtilities.Manhattan(nb, goal) };
                    open.Enqueue(newNode);
                }
            }

            return new List<Coord>();
        }
    }
}
