// COM5113 Full_Search_UI - WinForms Option A
// Generated by assistant

using System.Collections.Generic;

namespace FullSearch
{
    public class DepthFirst : IPathFinder
    {
        public string Name => "DepthFirst";

        public List<Coord> FindPath(int[,] terrain, Coord start, Coord goal)
        {
            int rows = terrain.GetLength(0), cols = terrain.GetLength(1);
            var visited = new bool[rows, cols];
            var stack = new Stack<SearchNode>();
            var startNode = new SearchNode(start);
            stack.Push(startNode);

            while (!stack.IsEmpty())
            {
                var node = stack.Pop();
                if (visited[node.Position.Row, node.Position.Col]) continue;
                visited[node.Position.Row, node.Position.Col] = true;

                if (node.Position.Equals(goal)) return SearchUtilities.BuildPathList(node);

                var neighbors = new List<Coord>(SearchUtilities.GetNeighbors(node.Position));
                for (int i = neighbors.Count - 1; i >= 0; i--)
                {
                    var nb = neighbors[i];
                    if (nb.Row < 0 || nb.Row >= rows || nb.Col < 0 || nb.Col >= cols) continue;
                    if (terrain[nb.Row, nb.Col] == 0) continue;
                    if (visited[nb.Row, nb.Col]) continue;
                    var newNode = new SearchNode(nb) { Predecessor = node };
                    stack.Push(newNode);
                }
            }

            return new List<Coord>();
        }
    }
}
