// COM5113 Full_Search_UI - WinForms Option A
// Generated by assistant

using System;
using System.Windows.Forms;

namespace FullSearch
{
    partial class MainForm
    {
        private System.ComponentModel.IContainer components = null;
        private Panel panelGrid;
        private ComboBox comboAlgorithm;
        private Button btnRun;
        private TextBox txtMapName;
        private Label lblMap;
        private Label lblAlg;
        private TextBox txtOutput;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.panelGrid = new Panel();
            this.comboAlgorithm = new ComboBox();
            this.btnRun = new Button();
            this.txtMapName = new TextBox();
            this.lblMap = new Label();
            this.lblAlg = new Label();
            this.txtOutput = new TextBox();

            this.SuspendLayout();
            // panelGrid
            this.panelGrid.Location = new System.Drawing.Point(12, 12);
            this.panelGrid.Name = "panelGrid";
            this.panelGrid.Size = new System.Drawing.Size(480, 480);
            this.panelGrid.TabIndex = 0;
            // comboAlgorithm
            this.comboAlgorithm.DropDownStyle = ComboBoxStyle.DropDownList;
            this.comboAlgorithm.Location = new System.Drawing.Point(510, 50);
            this.comboAlgorithm.Name = "comboAlgorithm";
            this.comboAlgorithm.Size = new System.Drawing.Size(200, 23);
            // btnRun
            this.btnRun.Location = new System.Drawing.Point(510, 120);
            this.btnRun.Name = "btnRun";
            this.btnRun.Size = new System.Drawing.Size(200, 30);
            this.btnRun.Text = "Run Search";
            this.btnRun.Click += new EventHandler(this.btnRun_Click);
            // txtMapName
            this.txtMapName.Location = new System.Drawing.Point(510, 20);
            this.txtMapName.Name = "txtMapName";
            this.txtMapName.Size = new System.Drawing.Size(200, 23);
            // lblMap
            this.lblMap.Location = new System.Drawing.Point(510, 0);
            this.lblMap.Size = new System.Drawing.Size(200, 20);
            this.lblMap.Text = "Map name (xxx from xxxMap.txt):";
            // lblAlg
            this.lblAlg.Location = new System.Drawing.Point(510, 30);
            this.lblAlg.Size = new System.Drawing.Size(200, 20);
            this.lblAlg.Text = "Algorithm:";
            // txtOutput
            this.txtOutput.Location = new System.Drawing.Point(12, 500);
            this.txtOutput.Multiline = true;
            this.txtOutput.Name = "txtOutput";
            this.txtOutput.ScrollBars = ScrollBars.Vertical;
            this.txtOutput.Size = new System.Drawing.Size(698, 140);
            // MainForm
            this.ClientSize = new System.Drawing.Size(722, 652);
            this.Controls.Add(this.panelGrid);
            this.Controls.Add(this.comboAlgorithm);
            this.Controls.Add(this.btnRun);
            this.Controls.Add(this.txtMapName);
            this.Controls.Add(this.lblMap);
            this.Controls.Add(this.lblAlg);
            this.Controls.Add(this.txtOutput);
            this.Name = "MainForm";
            this.Text = "Full Search - WinForms (Option A)";
            this.ResumeLayout(false);
            this.PerformLayout();
        }
    }
}
