// COM5113 Full_Search_UI - WinForms Option A
// Generated by assistant

using System.Collections.Generic;

namespace FullSearch
{
    public interface IPathFinder
    {
        string Name { get; }
        List<Coord> FindPath(int[,] terrain, Coord start, Coord goal);
    }
}
