// COM5113 Full_Search_UI - WinForms Option A
// Generated by assistant

using System;
using System.Windows.Forms;

namespace FullSearch
{
    static class Program
    {
        [STAThread]
        static void Main()
        {
            ApplicationConfiguration.Initialize();
            Application.Run(new MainForm());
        }
    }
}
