// COM5113 Full_Search_UI - WinForms Option A
// Generated by assistant

using System;
using System.Collections.Generic;

namespace FullSearch
{
    public struct Coord
    {
        public int Row { get; set; }
        public int Col { get; set; }

        public Coord(int r, int c) { Row = r; Col = c; }

        public override string ToString() => $"{Row} {Col}";

        public override bool Equals(object obj)
        {
            if (!(obj is Coord)) return false;
            var o = (Coord)obj;
            return Row == o.Row && Col == o.Col;
        }

        public override int GetHashCode() => HashCode.Combine(Row, Col);
    }

    public class SearchNode
    {
        public Coord Position { get; set; }
        public SearchNode Predecessor { get; set; }
        public int GCost { get; set; }
        public int HCost { get; set; }
        public int FCost => GCost + HCost;

        public SearchNode(Coord pos)
        {
            Position = pos;
            Predecessor = null;
            GCost = 0;
            HCost = 0;
        }
    }
}
